version: "3.9"

services:
  mongodb:
    image: mongo
    ports:
      - ${EXPOSE_MONGO_PORT:-27017}:27017
    volumes:
      - mongodb-data:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${APP_MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${APP_MONGO_INITDB_ROOT_PASSWORD}

  rabbitmq:
    image: rabbitmq:3.8.17-management
    ports:
      - ${EXPOSE_RABBITMQ_PORT:-5672}:5672
      - ${EXPOSE_RABBITMQ_MANAGEMENT_PORT:-15672}:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${APP_RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${APP_RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq-data:/data

volumes:
  mongodb-data:
    driver: local
  rabbitmq-data:
    driver: local
